/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as IndividualsRouteImport } from './routes/individuals'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CorporationsRouteImport } from './routes/corporations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWorkspaceScenarioScenarioIdRouteImport } from './routes/_authenticated/workspace.scenario.$scenarioId'
import { Route as AuthenticatedWorkspaceResultsRunIdRouteImport } from './routes/_authenticated/workspace.results.$runId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsRoute = IndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporationsRoute = CorporationsRouteImport.update({
  id: '/corporations',
  path: '/corporations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceScenarioScenarioIdRoute =
  AuthenticatedWorkspaceScenarioScenarioIdRouteImport.update({
    id: '/scenario/$scenarioId',
    path: '/scenario/$scenarioId',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceResultsRunIdRoute =
  AuthenticatedWorkspaceResultsRunIdRouteImport.update({
    id: '/results/$runId',
    path: '/results/$runId',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/docs': typeof DocsRouteWithChildren
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/api/assistant': typeof ApiAssistantRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/': typeof DocsIndexRoute
  '/workspace/results/$runId': typeof AuthenticatedWorkspaceResultsRunIdRoute
  '/workspace/scenario/$scenarioId': typeof AuthenticatedWorkspaceScenarioScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/api/assistant': typeof ApiAssistantRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs': typeof DocsIndexRoute
  '/workspace/results/$runId': typeof AuthenticatedWorkspaceResultsRunIdRoute
  '/workspace/scenario/$scenarioId': typeof AuthenticatedWorkspaceScenarioScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/docs': typeof DocsRouteWithChildren
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/api/assistant': typeof ApiAssistantRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/workspace/results/$runId': typeof AuthenticatedWorkspaceResultsRunIdRoute
  '/_authenticated/workspace/scenario/$scenarioId': typeof AuthenticatedWorkspaceScenarioScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/docs'
    | '/individuals'
    | '/investors'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/workspace'
    | '/api/assistant'
    | '/auth/callback'
    | '/docs/'
    | '/workspace/results/$runId'
    | '/workspace/scenario/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/individuals'
    | '/investors'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/workspace'
    | '/api/assistant'
    | '/auth/callback'
    | '/docs'
    | '/workspace/results/$runId'
    | '/workspace/scenario/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/docs'
    | '/individuals'
    | '/investors'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/workspace'
    | '/api/assistant'
    | '/auth/callback'
    | '/docs/'
    | '/_authenticated/workspace/results/$runId'
    | '/_authenticated/workspace/scenario/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CorporationsRoute: typeof CorporationsRoute
  DocsRoute: typeof DocsRouteWithChildren
  IndividualsRoute: typeof IndividualsRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals': {
      id: '/individuals'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof IndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporations': {
      id: '/corporations'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof CorporationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/scenario/$scenarioId': {
      id: '/_authenticated/workspace/scenario/$scenarioId'
      path: '/scenario/$scenarioId'
      fullPath: '/workspace/scenario/$scenarioId'
      preLoaderRoute: typeof AuthenticatedWorkspaceScenarioScenarioIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/results/$runId': {
      id: '/_authenticated/workspace/results/$runId'
      path: '/results/$runId'
      fullPath: '/workspace/results/$runId'
      preLoaderRoute: typeof AuthenticatedWorkspaceResultsRunIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceResultsRunIdRoute: typeof AuthenticatedWorkspaceResultsRunIdRoute
  AuthenticatedWorkspaceScenarioScenarioIdRoute: typeof AuthenticatedWorkspaceScenarioScenarioIdRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceResultsRunIdRoute:
      AuthenticatedWorkspaceResultsRunIdRoute,
    AuthenticatedWorkspaceScenarioScenarioIdRoute:
      AuthenticatedWorkspaceScenarioScenarioIdRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CorporationsRoute: CorporationsRoute,
  DocsRoute: DocsRouteWithChildren,
  IndividualsRoute: IndividualsRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
