/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as IndividualsRouteImport } from './routes/individuals'
import { Route as CorporationsRouteImport } from './routes/corporations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsRoute = IndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporationsRoute = CorporationsRouteImport.update({
  id: '/corporations',
  path: '/corporations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/pilot': typeof PilotRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/pilot': typeof PilotRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporations': typeof CorporationsRoute
  '/individuals': typeof IndividualsRoute
  '/investors': typeof InvestorsRoute
  '/pilot': typeof PilotRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/individuals'
    | '/investors'
    | '/pilot'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/individuals'
    | '/investors'
    | '/pilot'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/corporations'
    | '/individuals'
    | '/investors'
    | '/pilot'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CorporationsRoute: typeof CorporationsRoute
  IndividualsRoute: typeof IndividualsRoute
  InvestorsRoute: typeof InvestorsRoute
  PilotRoute: typeof PilotRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals': {
      id: '/individuals'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof IndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporations': {
      id: '/corporations'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof CorporationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CorporationsRoute: CorporationsRoute,
  IndividualsRoute: IndividualsRoute,
  InvestorsRoute: InvestorsRoute,
  PilotRoute: PilotRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
